# ================================
# AI Terminal - Theme Configuration
# ================================
# 主题配置文件，支持多种主题切换

# 默认主题
[settings]
default_theme = "dracula"

# =================
# Dracula 主题配置
# =================
[dracula]
name = "Dracula"
id = "dracula"

# CSS 变量配置
[dracula.css_variables]
# 背景色
"--bg-primary" = "#282a36"
"--bg-secondary" = "#21222c"
"--bg-tertiary" = "#1e1f29"
"--bg-quaternary" = "#44475a"

# 边框色
"--border-primary" = "#44475a"
"--border-secondary" = "#6272a4"

# 文本色
"--text-primary" = "#f8f8f2"
"--text-secondary" = "#f8f8f2"
"--text-tertiary" = "#6272a4"

# 强调色
"--accent-blue" = "#8be9fd"
"--accent-green" = "#50fa7b"
"--accent-yellow" = "#f1fa8c"
"--accent-red" = "#ff5555"
"--accent-purple" = "#bd93f9"
"--accent-pink" = "#ff79c6"
"--accent-orange" = "#ffb86c"
"--terminal-green" = "#50fa7b"

# 阴影
"--shadow-light" = "rgba(0, 0, 0, 0.1)"
"--shadow-medium" = "rgba(0, 0, 0, 0.25)"
"--shadow-heavy" = "rgba(0, 0, 0, 0.6)"

# 过渡效果
"--transition-smooth" = "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)"
"--transition-spring" = "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"

# 圆角
"--radius-small" = "4px"
"--radius-medium" = "8px"
"--radius-large" = "12px"
"--radius-full" = "50%"

# xterm.js 终端主题配置
[dracula.xterm_theme]
background = "#282a36"
foreground = "#f8f8f2"
cursor = "#f8f8f2"
selection = "#44475a"
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#8be9fd"
magenta = "#bd93f9"
cyan = "#8be9fd"
white = "#f8f8f2"
brightBlack = "#6272a4"
brightRed = "#ff6e6e"
brightGreen = "#69ff94"
brightYellow = "#ffffa5"
brightBlue = "#d6acff"
brightMagenta = "#ff92df"
brightCyan = "#a4ffff"
brightWhite = "#ffffff"

# 终端配置
[dracula.terminal_config]
fontFamily = "'CaskaydiaCove Nerd Font Mono', 'CaskaydiaMono Nerd Font'"
fontSize = 14
letterSpacing = 0.5
lineHeight = 1.2
scrollback = 1000
allowTransparency = false
cursorBlink = true

# ===============
# Light 主题配置
# ===============
[light]
name = "Light"
id = "light"

# CSS 变量配置
[light.css_variables]
# 背景色
"--bg-primary" = "#ffffff"
"--bg-secondary" = "#f8f9fa"
"--bg-tertiary" = "#f1f3f4"
"--bg-quaternary" = "#e8eaed"

# 边框色
"--border-primary" = "#dadce0"
"--border-secondary" = "#9aa0a6"

# 文本色
"--text-primary" = "#202124"
"--text-secondary" = "#5f6368"
"--text-tertiary" = "#9aa0a6"

# 强调色
"--accent-blue" = "#1a73e8"
"--accent-green" = "#34a853"
"--accent-yellow" = "#fbbc04"
"--accent-red" = "#ea4335"
"--accent-purple" = "#9c27b0"
"--accent-pink" = "#e91e63"
"--accent-orange" = "#ff6d01"
"--terminal-green" = "#34a853"

# 阴影
"--shadow-light" = "rgba(0, 0, 0, 0.1)"
"--shadow-medium" = "rgba(0, 0, 0, 0.25)"
"--shadow-heavy" = "rgba(0, 0, 0, 0.6)"

# 过渡效果
"--transition-smooth" = "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)"
"--transition-spring" = "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"

# 圆角
"--radius-small" = "4px"
"--radius-medium" = "8px"
"--radius-large" = "12px"
"--radius-full" = "50%"

# xterm.js 终端主题配置
[light.xterm_theme]
background = "#ffffff"
foreground = "#202124"
cursor = "#1a73e8"
selection = "#e8f0fe"
black = "#202124"
red = "#ea4335"
green = "#34a853"
yellow = "#fbbc04"
blue = "#1a73e8"
magenta = "#9c27b0"
cyan = "#00acc1"
white = "#f8f9fa"
brightBlack = "#5f6368"
brightRed = "#ea4335"
brightGreen = "#34a853"
brightYellow = "#fbbc04"
brightBlue = "#1a73e8"
brightMagenta = "#9c27b0"
brightCyan = "#00acc1"
brightWhite = "#ffffff"

# 终端配置
[light.terminal_config]
fontFamily = "'CaskaydiaCove Nerd Font Mono', 'CaskaydiaMono Nerd Font', 'FiraCode Nerd Font', 'JetBrains Mono Nerd Font', 'Hack Nerd Font', 'Source Code Pro Nerd Font', 'MesloLGS Nerd Font', 'DejaVu Sans Mono Nerd Font', 'Cascadia Code NF', 'SF Mono', 'Monaco', monospace"
fontSize = 14
letterSpacing = 0.5
lineHeight = 1.2
scrollback = 1000
allowTransparency = false
cursorBlink = true
